<a href="https://colab.research.google.com/github/Nishaanth54/240901066_NumPy4/blob/main/240901066_NumPy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\n Vector addition")
print(a+b)
print("\n Vector subtraction")
print(a-b)
print("\n Vector multiplication")
print(a*b)
print("\n Vector division")
print(a/b)
print("\n Vector Dot Product")
print(a.dot(b))
print("\n Scalar multiplication")
sclr=5
print("\n Scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)
#Numpy.Vectorize method
def my_func(x,y):
#"Return x-y if x>y,otherwise return x+y"
  if x>y:
    return x-y
  else:
    return x+y
  print("\n\n Numpy.Vectorize method")
  print("Return x-y if x>y, otherwise return x+y")
  arr1=[10,4,20]
  arr2=[2,3,30]
  vec_func=np.vetorize(my_func)
  print("array1:",arr1)
  print("array2:",arr2)
  print("result:",vec_func(arr1,arr2))


Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

 Vector addition
[12 24 35 48 60]

 Vector subtraction
[ 8 16 25 32 40]

 Vector multiplication
[ 20  80 150 320 500]

 Vector division
[5. 5. 6. 5. 5.]

 Vector Dot Product
1070

 Scalar multiplication

 Scalar value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]
